services:
    postgresql:
        container_name: database
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: characters
            POSTGRES_USER: pharod
            POSTGRES_PASSWORD: 112358
        volumes:
            - data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network
        command: ["postgres", "-c", "log_statement=all"]

volumes:
    data:

networks:
    app-network:
        driver: bridge